from db import Base
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.sql  import func
from sqlalchemy.orm import relationship
from sqlalchemy import text

class User(Base):
    __tablename__ = "users"
    id = Column(Integer, primary_key=True, index=True)
    name = Column(String)
    email = Column(String, unique=True, index=True)
    password = Column(String)
    phonenumber = Column(String(10))
    stories = relationship("Story", back_populates="owner")

class Story(Base):
    __tablename__ = "stories"

    id = Column(Integer, primary_key=True, index=True)

    user_id = Column(
        Integer,
        ForeignKey("users.id"),
        nullable=False
    )

    # Story Information
    title = Column(String(255), nullable=False)

    description = Column(Text)

    # This will store the entire story generated by Gemini
    story_content = Column(Text)

    # Story Options
    theme = Column(String(100))

    genre = Column(String(100))

    language = Column(String(50))

    age_group = Column(String(50))

    story_length = Column(String(50))

    art_style = Column(String(100))

    moral = Column(String(255))

    # Character Information
    character_name = Column(String(100))

    character_type = Column(String(100))

    # Future Cover Image
    cover_image = Column(Text)

    # Status
    status = Column(
        String(50),
        default="Draft"
    )

    visibility = Column(
        String(50),
        default="Private"
    )

    # Timestamps
    created_at = Column(
        DateTime(timezone=True),
        server_default=func.now()
    )

    updated_at = Column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now()
    )

    last_opened = Column(DateTime(timezone=True))

    owner = relationship(
        "User",
        back_populates="stories"
    )